'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='easier-v1';
const uid=()=>crypto.randomUUID();
const today=()=>Planning.dateKey(new Date());
const fresh=()=>({plan:Planning.defaults(),tasks:[],notes:[],energy:'',routines:[{id:'r1',text:'Drink a glass of water'},{id:'r2',text:'Take a movement break'},{id:'r3',text:'Set out one thing for tomorrow'}],checks:[],day:today(),autoOrganize:true,localAI:true,localVoice:true});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const minutes=n=>Math.max(1,Math.min(1440,Math.round(Number(n)||15)));
function normalize(s){if(!s||!Array.isArray(s.tasks)||!Array.isArray(s.notes)||!Array.isArray(s.routines))throw Error('Not an app backup');const clean=fresh();return {...clean,plan:Planning.normalizePlan(s.plan),energy:['Low','Steady','High'].includes(s.energy)?s.energy:'',tasks:s.tasks.slice(0,1000).map(t=>({id:String(t.id||uid()),text:String(t.text||'Untitled task').slice(0,5000),done:!!t.done,...Planning.taskFields(t),minutes:minutes(t.minutes),estimateSource:t.estimateSource||'placeholder',priority:[1,2,3].includes(+t.priority)?+t.priority:2,context:String(t.context||'').slice(0,1000),steps:(Array.isArray(t.steps)?t.steps:[]).slice(0,40).map(x=>({text:String(x.text||'').slice(0,300),minutes:minutes(x.minutes||5),done:!!x.done}))})),notes:s.notes.slice(0,1000).map(n=>({id:String(n.id||uid()),text:String(n.text||'').slice(0,5000),created:n.created||Date.now(),items:Array.isArray(n.items)?n.items.slice(0,30).map(x=>({text:String(x.text||'').slice(0,300),category:['Action','Idea','Question','Note'].includes(x.category)?x.category:'Note',minutes:minutes(x.minutes),added:!!x.added})):null})),routines:s.routines.slice(0,100).map(r=>({id:String(r.id||uid()),text:String(r.text||'').slice(0,200)})),checks:Array.isArray(s.checks)?s.checks.map(String):[],day:s.day||today(),autoOrganize:s.autoOrganize!==false,localAI:s.localAI!==false,localVoice:s.localVoice!==false};}
let state;try{state=normalize(JSON.parse(localStorage.getItem(KEY))||fresh())}catch{state=fresh()}
let showAll=false,selectedTask='',editing=null,editingRoutine=null,review=null,requestBusy=false,toastTimer,saveFailed=false;
let connection={ready:false,voice:false};
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));saveFailed=false;$('#save-status').textContent='Saved on this browser.'}catch{saveFailed=true;$('#save-status').textContent='Storage full or unavailable — export your data.';toast('Could not save to this browser. Export before closing.')}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),6500)}
function syncDay(){if(state.day!==today()){state.day=today();state.checks=[];save()}}
function taskOrder(){return state.tasks.filter(t=>t.date===(state.plan.selectedDate||today())&&(!state.plan.domainFilter||state.plan.domainFilter==='all'||t.domain===state.plan.domainFilter)).sort((a,b)=>Number(a.done)-Number(b.done)||a.priority-b.priority)}
function limit(){return document.body.classList.contains('quiet')?1:showAll?Infinity:({Low:1,Steady:3,High:5}[state.energy]||Infinity)}
function render(){syncDay();let ordered=taskOrder(),pending=ordered.filter(t=>!t.done),allowed=new Set(pending.slice(0,limit()).map(t=>t.id));let visible=pending.filter(t=>allowed.has(t.id));$('#count').textContent=`${ordered.filter(t=>t.done).length} / ${ordered.length} done`;
$('#plan-summary').textContent=visible.length?`${visible.length} shown · about ${visible.reduce((a,t)=>a+t.minutes,0)} min in total${visible.some(t=>t.estimateSource==='placeholder')?' · includes starter estimates':''}`:'Your next small step can start here.';
$('#tasks').innerHTML=ordered.length?ordered.map(t=>`<div class="task ${t.done?'done':''} ${(!t.done&&!allowed.has(t.id))||(t.done&&limit()!==Infinity)?'energy-hidden':''}"><input type="checkbox" data-check="${esc(t.id)}" aria-label="Complete ${esc(t.text)}" ${t.done?'checked':''}><div class="task-main"><div class="task-title">${esc(t.text)}</div><div class="task-meta"><span class="pill ${t.domain}">${t.domain==='work'?'Work':'Personal'}${t.start?' · '+t.start:''}</span><span class="pill">~${t.minutes} min${t.estimateSource==='placeholder'?' · starter estimate':t.estimateSource==='AI'?' · AI estimate':''}</span>${t.priority===1?'<span class="pill">Important today</span>':''}${t.steps.length?`<span class="pill">${t.steps.filter(s=>s.done).length}/${t.steps.length} steps</span>`:''}</div>${t.steps.length?`<details><summary class="small" style="margin-top:8px;cursor:pointer">View steps</summary><ul class="substeps">${t.steps.map((s,i)=>`<li><label><input type="checkbox" data-step-task="${esc(t.id)}" data-step-index="${i}" ${s.done?'checked':''}><span>${esc(s.text)}</span></label><small>~${s.minutes} min</small></li>`).join('')}</ul></details>`:''}<div class="task-actions"><button data-edit="${esc(t.id)}">Edit / AI steps</button><button data-start="${esc(t.id)}">Help me start</button><button data-delete="${esc(t.id)}">Remove</button></div></div></div>`).join(''):'<p style="padding:22px 0">No tasks yet. Add one thing; we’ll make it smaller together.</p>';
$('#show-all').classList.toggle('hidden',pending.length<=visible.length&&(!ordered.some(t=>t.done)||limit()===Infinity));$('#show-all').textContent=`Show full list (${ordered.length})`;
$$('[data-energy]').forEach(b=>{let active=b.dataset.energy===state.energy;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active)});
$('#energy-note').textContent=({Low:'One task at a time. AI will make the first step just 1–2 minutes.',Steady:'Three tasks in view. AI will look for a first step under 5 minutes.',High:'Five tasks in view. Keep your first step simple, even with momentum.'})[state.energy]||'Skip if you prefer. Choose an energy level to make your visible plan smaller.';
if(showAll&&state.energy)$('#energy-note').textContent='Full list shown by your choice. '+state.energy+' energy still guides the size of AI starting steps.';
if(!pending.some(t=>t.id===selectedTask))selectedTask=pending[0]?.id||'';
$('#start-task').innerHTML=pending.length?pending.map(t=>`<option value="${esc(t.id)}">${esc(t.text)}</option>`).join(''):'<option value="">Add a task to begin</option>';$('#start-task').value=selectedTask;renderStart();renderNotes();renderRoutines();$('#auto-organize').checked=state.autoOrganize;save();if(window.renderPlanning)window.renderPlanning();}
function renderStart(){let t=state.tasks.find(t=>t.id===selectedTask&&!t.done);if(!t){$('#start-content').innerHTML='<div class="next-step"><h3>What would feel good to get off your mind?</h3><p>Add one task on the left. We’ll find a practical first action.</p></div>';return}let i=t.steps.findIndex(s=>!s.done),next=t.steps[i];$('#start-content').innerHTML=next?`<div class="next-step"><div class="step-position">Step ${i+1} of ${t.steps.length} · ~${next.minutes} min</div><h3>${esc(next.text)}</h3><p>Only this step needs your attention right now.</p></div><div class="start-actions"><button class="primary" data-next="${esc(t.id)}" data-next-index="${i}">I did this step</button><button data-edit="${esc(t.id)}">Adjust the steps</button></div>`:t.steps.length?`<div class="next-step"><h3>You’ve worked through the steps.</h3><p>If there’s nothing else to do, close this task.</p></div><button class="primary" data-complete="${esc(t.id)}">Mark task complete</button>`:`<div class="next-step"><div class="step-position">~${t.minutes} min · rough estimate</div><h3>Let’s find the first physical action.</h3><p>Tell AI what’s making this hard. It will suggest relevant steps and times for you to review.</p></div><div class="start-actions"><button class="primary" data-edit="${esc(t.id)}">Find my starting steps</button><button data-complete="${esc(t.id)}">Already done</button></div>`;}
function renderNotes(){$('#notes').innerHTML=state.notes.length?state.notes.map(n=>`<article class="resource"><div class="note-title"><h3>${n.items?'An organized thought':'A thought to untangle'}</h3><small>${new Date(n.created).toLocaleDateString()}</small></div>${n.items?['Action','Idea','Question','Note'].map(category=>{let items=n.items.map((x,i)=>({...x,i})).filter(x=>x.category===category);return items.length?`<div class="log-group"><div class="tag">${category==='Action'?'Things to do':category==='Idea'?'Ideas to keep':category==='Question'?'Things to find out':'Notes'}</div>${items.map(x=>`<div class="log-item"><p>${esc(x.text)}</p>${category==='Action'?`<small>~${x.minutes} min</small>`:''}<button data-add-item="${esc(n.id)}" data-item-index="${x.i}" ${x.added?'disabled':''}>${x.added?'Added to my day':'Add to my day'}</button></div>`).join('')}</div>`:''}).join(''):''}<details ${n.items?'':'open'}><summary class="small">Original thought</summary><p class="raw">${esc(n.text)}</p></details><div class="actions"><button data-organize="${esc(n.id)}">${n.items?'Reorganize':'Organize'} with local AI</button><button data-note-delete="${esc(n.id)}">Remove thought</button></div></article>`).join(''):'<p style="padding:25px 0">A clear space. Say or type whatever comes to mind.</p>';}
function renderRoutines(){$('#routine-list').innerHTML=state.routines.map(r=>`<div class="routine-row"><input type="checkbox" data-routine="${esc(r.id)}" aria-label="${esc(r.text)}" ${state.checks.includes(r.id)?'checked':''}><span class="routine-text">${esc(r.text)}</span><div class="actions"><button data-routine-edit="${esc(r.id)}" class="mini">Edit</button><button data-routine-delete="${esc(r.id)}" class="mini">Remove</button></div></div>`).join('');}
function page(id){$$('.page').forEach(e=>e.classList.toggle('hidden',e.id!==id));$$('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.page===id);b.setAttribute('aria-current',b.dataset.page===id?'page':'false')});stopRecording();if(window.renderPlanning)window.renderPlanning();}
async function refreshConnection(){if(location.protocol==='file:'){connection={ready:false,voice:false};$('#ai-status').textContent='File version: open the local app for AI and dictation.';$('#setup-instructions').innerHTML='<p><a href="http://localhost:5173">Open the local app</a>. Export your data here first, then import it there to keep your entries.</p>';}else{try{let r=await fetch('/api/status',{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error();connection=await r.json();$('#ai-status').textContent=connection.ready?`On-device AI ready · ${connection.model} · no cloud sharing`:'On-device AI is starting or needs its model.';$('#setup-instructions').innerHTML=connection.ready?'':`<p class="small">Start the app with <code>Start app.command</code>. If setup is incomplete, see <code>README.md</code>.</p>`;}catch{connection={ready:false,voice:false};$('#ai-status').textContent='Local AI server unavailable. Start the app to reconnect.';$('#setup-instructions').innerHTML='<p class="small">Run Start app.command in the app folder. Your saved tasks are still available.</p>';}}
$('#connection-detail').textContent=connection.ready?`Task planning runs on this Mac using ${connection.model}. Your text is never sent to a cloud model.`:'Local text AI is not ready yet. No cloud fallback is used.';$('#voice-support').textContent=connection.voice?'Local speech model ready. Dictate records up to 90 seconds; press Stop to transcribe.':'Local speech model is not ready. Typing remains available; no browser cloud dictation is used.';$('#ai-consent').checked=state.localAI;$('#voice-consent').checked=state.localVoice;}
function showSettings(){$('#prefs').showModal();refreshConnection()}
async function ai(kind,text,context=''){if(!state.localAI)throw Error('Enable on-device AI in Data & AI settings.');if(!connection.ready)throw Error('The local AI model is not ready. Check Data & AI settings, then try again.');if(requestBusy)throw Error('One local AI request is already running. Please wait for it to finish.');requestBusy=true;try{let r=await fetch('/api/assist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,text,context,energy:state.energy||'Steady'}),signal:AbortSignal.timeout(180000)});let result=await r.json();if(!r.ok)throw Error(result.error||'Local AI could not finish. Your original text is safe.');return result;}catch(e){if(e.name==='TimeoutError'||e.name==='AbortError')throw Error('Local AI took too long. Your original text is safe. Try a shorter task.');throw e;}finally{requestBusy=false;}}
function openTask(id,text=''){editing=id?JSON.parse(JSON.stringify(state.tasks.find(t=>t.id===id))):{id:uid(),...Planning.taskFields({date:state.plan.selectedDate||today()}),text,minutes:15,estimateSource:'placeholder',priority:2,context:'',done:false,steps:[],isNew:true};if(!editing)return;$('#task-title').value=editing.text;$('#task-minutes').value=editing.minutes;$('#task-priority').value=editing.priority;$('#task-context').value=editing.context;$('#task-domain').value=editing.domain||'personal';$('#task-date').value=editing.date||'';$('#task-start').value=editing.start||'';$('#task-reminder').value=editing.reminder??10;$('#task-schedule-note').textContent=editing.calendarEventId?'Linked to Calendar. Publish again after changing the time; deleting here will not remove its Calendar event.':'Leave the start time blank to let weekly planning find a space.';$('#task-dialog-title').textContent=editing.isNew?'Make it doable':'Edit task & starting steps';$('#task-error').classList.add('hidden');renderEditorSteps();$('#task-dialog').showModal();}
function voiceField(id,value,label,max=300){return `<div class="voice-field"><input id="${id}" aria-label="${esc(label)}" value="${esc(value)}" maxlength="${max}" required><button type="button" class="voice" data-voice="${id}">Dictate</button></div>`;}
function renderEditorSteps(){$('#task-editor-steps').innerHTML=editing.steps.length?`<h3>Your steps</h3>${editing.steps.map((s,i)=>`<div class="review-row">${voiceField('edit-step-'+i,s.text,'Step '+(i+1))}<div class="step-help"><label for="edit-time-${i}" class="small">Minutes</label><input id="edit-time-${i}" value="${s.minutes}" inputmode="numeric" pattern="[0-9]+" required><button type="button" class="voice" data-voice="edit-time-${i}">Dictate</button><button type="button" data-remove-step="${i}" class="mini">Remove</button></div></div>`).join('')}`:'';}
function readEditorSteps(){editing.steps=editing.steps.map((s,i)=>({...s,text:$('#edit-step-'+i).value.trim(),minutes:parseMinutes($('#edit-time-'+i).value)}));}
function parseMinutes(value){let n=Number(value);if(!Number.isInteger(n)||n<1||n>1440)throw Error('Use a whole number between 1 and 1440 for minutes.');return n;}
function errorIn(selector,message){$(selector).textContent=message;$(selector).classList.remove('hidden')}
async function suggest(){let b=$('#suggest-steps');try{readEditorSteps();if(!$('#task-title').value.trim())throw Error('Add a task title first.');b.disabled=true;b.textContent='Thinking on this Mac…';$('#task-error').classList.add('hidden');let result=await ai('breakdown',$('#task-title').value.trim(),$('#task-context').value.trim());if(!$('#task-dialog').open)return;openReview('steps',result,{taskId:editing.id,title:$('#task-title').value.trim()});}catch(e){errorIn('#task-error',e.message)}finally{b.disabled=false;b.textContent='Suggest steps & time with AI';}}
function openReview(type,result,source){review={type,source,items:result.items,assumptions:result.assumptions};$('#review-title').textContent=type==='steps'?'A smaller path to done':'Your thought, made into a list';$('#review-description').textContent=type==='steps'?'Edit or uncheck anything. Accepted steps replace this task’s existing steps; their times become its estimate.':'Check the wording and groups. Save this list, then choose which items belong on your day. Your original stays intact.';$('#review-assumptions').textContent=result.assumptions?`AI assumptions: ${result.assumptions}`:'';$('#review-error').classList.add('hidden');$('#review-list').innerHTML=result.items.map((x,i)=>`<div class="review-row"><label class="checkline"><input type="checkbox" id="review-keep-${i}" checked><span>Keep ${type==='steps'?'step':'item'} ${i+1}</span></label>${voiceField('review-text-'+i,x.text,`Suggestion ${i+1}`)}<div class="line"><div id="review-timing-${i}" class="line ${type==='dump'&&x.category!=='Action'?'hidden':''}"><label for="review-min-${i}" class="small">Estimated minutes</label><input class="estimate" id="review-min-${i}" value="${x.minutes}" inputmode="numeric" pattern="[0-9]+"><button type="button" class="voice" data-voice="review-min-${i}">Dictate</button></div>${type==='dump'?`<label class="sr-only" for="review-category-${i}">Category ${i+1}</label><select id="review-category-${i}" data-review-category="${i}">${['Action','Idea','Question','Note'].map(c=>`<option ${c===x.category?'selected':''}>${c}</option>`).join('')}</select>`:''}</div></div>`).join('');$('#review-dialog').showModal();}
async function organize(id){let note=state.notes.find(n=>n.id===id);if(!note)return;let buttons=$$('[data-organize]').filter(b=>b.dataset.organize===id);buttons.forEach(b=>{b.disabled=true;b.textContent='Organizing on this Mac…'});toast('Your thought is saved. Local AI is finding the useful parts…');try{let result=await ai('organize',note.text);if(!state.notes.some(n=>n.id===id))return;openReview('dump',result,{noteId:id});}catch(e){toast(e.message)}finally{renderNotes()}}
async function capture(field){const text=$(field).value.trim();if(!text)return;let note={id:uid(),text,created:Date.now(),items:null};state.notes.unshift(note);save();if(saveFailed){state.notes.shift();return}$(field).value='';renderNotes();toast('Original thought saved.');if(state.autoOrganize)await organize(note.id);}
$('#task-form').onsubmit=e=>{e.preventDefault();const text=$('#new-task').value.trim();if(text)openTask(null,text);};
$('#edit-task-form').onsubmit=e=>{e.preventDefault();try{readEditorSteps();const text=$('#task-title').value.trim();if(!text)throw Error('Add a task title.');let estimate=parseMinutes($('#task-minutes').value);const chosenDate=$('#task-date').value,chosenStart=$('#task-start').value;if(chosenDate&&!Planning.validDate(chosenDate))throw Error('Choose a valid date.');if(chosenStart&&!chosenDate)throw Error('Choose a date for this start time.');if(chosenStart&&Planning.stamp(chosenDate,chosenStart)+estimate*60000>Planning.stamp(Planning.addDays(chosenDate,1)))throw Error('This task extends past midnight. Choose an earlier start or split the task.');const task={...editing,date:chosenDate,start:chosenStart,domain:$('#task-domain').value,reminder:+$('#task-reminder').value,text,minutes:estimate,priority:+$('#task-priority').value,context:$('#task-context').value.trim()};if(estimate!==editing.minutes)task.estimateSource='manual';delete task.isNew;let i=state.tasks.findIndex(t=>t.id===task.id);if(i<0)state.tasks.push(task);else state.tasks[i]=task;selectedTask=task.id;if(task.date){state.plan.selectedDate=task.date;state.plan.week=Planning.monday(task.date);}$('#task-dialog').close();$('#new-task').value='';render();toast('Task saved. Your next step is ready.')}catch(err){errorIn('#task-error',err.message)}};
$('#suggest-steps').onclick=suggest;$('#manual-step').onclick=()=>{try{readEditorSteps();editing.steps.push({text:'',minutes:5,done:false});renderEditorSteps()}catch(e){errorIn('#task-error',e.message)}};
$('#review-form').onsubmit=e=>{e.preventDefault();try{let items=review.items.map((x,i)=>({text:$('#review-text-'+i).value.trim(),minutes:$('#review-keep-'+i).checked&&(review.type==='steps'||$('#review-category-'+i).value==='Action')?parseMinutes($('#review-min-'+i).value):1,keep:$('#review-keep-'+i).checked,category:review.type==='dump'?$('#review-category-'+i).value:'Action'})).filter(x=>x.keep);if(!items.length||items.some(x=>!x.text))throw Error('Keep at least one suggestion, with text.');if(review.type==='steps'){if(!editing||editing.id!==review.source.taskId)throw Error('This task has changed. Generate a fresh set of steps.');if($('#task-title').value.trim()!==review.source.title)throw Error('The task title changed. Generate fresh suggestions for the new task.');editing.steps=items.map(x=>({text:x.text,minutes:x.minutes,done:false}));editing.minutes=items.reduce((a,x)=>a+x.minutes,0);editing.estimateSource='AI';$('#task-minutes').value=editing.minutes;renderEditorSteps();toast('Steps accepted. Save the task to keep them.')}else{let note=state.notes.find(n=>n.id===review.source.noteId);if(!note)throw Error('This thought was removed.');note.items=items.map(x=>({text:x.text,minutes:x.minutes,category:x.category,added:false}));save();renderNotes();page('inbox');toast('Organized list saved. Choose what belongs on your day.')}$('#review-dialog').close();review=null;}catch(err){errorIn('#review-error',err.message)}};
$('#dump-form').onsubmit=e=>{e.preventDefault();capture('#dump-text')};$('#inbox-form').onsubmit=e=>{e.preventDefault();capture('#brain-inbox-input')};
$('#routine-form').onsubmit=e=>{e.preventDefault();let text=$('#routine-input').value.trim();if(!text)return;state.routines.push({id:uid(),text});$('#routine-input').value='';render()};$('#edit-routine-form').onsubmit=e=>{e.preventDefault();let text=$('#routine-edit-text').value.trim();if(!text)return;let r=state.routines.find(r=>r.id===editingRoutine);if(r)r.text=text;$('#routine-dialog').close();render()};
$('#start-task').onchange=e=>{selectedTask=e.target.value;renderStart()};$('#show-all').onclick=()=>{showAll=true;document.body.classList.remove('quiet');$('#quiet').setAttribute('aria-pressed','false');$('#quiet').textContent='Low-overwhelm mode';render()};$('#skip-energy').onclick=()=>{state.energy='';showAll=true;render()};$('#quiet').onclick=()=>{let active=document.body.classList.toggle('quiet');$('#quiet').setAttribute('aria-pressed',active);$('#quiet').textContent=active?'Show full day':'Low-overwhelm mode';page('today');render()};
$('#auto-organize').onchange=e=>{state.autoOrganize=e.target.checked;save()};$('#ai-consent').onchange=e=>{state.localAI=e.target.checked;save()};$('#voice-consent').onchange=e=>{state.localVoice=e.target.checked;if(!state.localVoice)stopRecording();save()};$('#settings').onclick=showSettings;$('#ai-settings').onclick=showSettings;$('#refresh-ai').onclick=refreshConnection;
document.addEventListener('change',e=>{let d=e.target.dataset;if(d.reviewCategory!==undefined)$('#review-timing-'+d.reviewCategory).classList.toggle('hidden',e.target.value!=='Action');if(d.check){let t=state.tasks.find(t=>t.id===d.check);if(t)t.done=e.target.checked;render()}if(d.stepTask){let t=state.tasks.find(t=>t.id===d.stepTask);if(t)t.steps[+d.stepIndex].done=e.target.checked;save();renderStart()}if(d.routine){state.checks=state.checks.filter(id=>id!==d.routine);if(e.target.checked)state.checks.push(d.routine);save()}});
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let d=b.dataset;if(d.page)page(d.page);if(d.close){stopRecording();$('#'+d.close).close()}if(d.energy){state.energy=d.energy;showAll=false;selectedTask='';render()}if(d.edit)openTask(d.edit);if(d.start){selectedTask=d.start;renderStart();$('.start-panel').scrollIntoView({block:'center',behavior:'auto'})}if(d.next){let t=state.tasks.find(t=>t.id===d.next);t.steps[+d.nextIndex].done=true;render();toast('One step done. That counts.')}if(d.complete){let t=state.tasks.find(t=>t.id===d.complete);t.done=true;render();toast('Task complete.')}if(d.delete){state.tasks=state.tasks.filter(t=>t.id!==d.delete);render()}if(d.organize)organize(d.organize);if(d.noteDelete){state.notes=state.notes.filter(n=>n.id!==d.noteDelete);renderNotes();save()}if(d.addItem){let note=state.notes.find(n=>n.id===d.addItem),item=note.items[+d.itemIndex];if(item.added)return;let task={id:uid(),...Planning.taskFields({date:state.plan.selectedDate||today()}),text:item.text,minutes:item.category==='Action'?item.minutes:15,estimateSource:item.category==='Action'?'AI':'placeholder',priority:2,done:false,steps:[],context:''};state.tasks.push(task);item.added=true;selectedTask=task.id;render();toast('Added to your day.')}if(d.routineEdit){editingRoutine=d.routineEdit;$('#routine-edit-text').value=state.routines.find(r=>r.id===editingRoutine).text;$('#routine-dialog').showModal()}if(d.routineDelete){state.routines=state.routines.filter(r=>r.id!==d.routineDelete);render()}if(d.removeStep!==undefined){try{readEditorSteps();editing.steps.splice(+d.removeStep,1);renderEditorSteps()}catch(err){errorIn('#task-error',err.message)}}if(d.voice)dictate(d.voice,b)});
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='a-little-easier-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onchange=async e=>{try{let file=e.target.files[0];if(!file)return;if(file.size>3000000)throw Error('Backup is too large.');let incoming=normalize(JSON.parse(await file.text()));for(let key of ['tasks','notes','routines']){let ids=new Set(state[key].map(x=>x.id));state[key].push(...incoming[key].filter(x=>!ids.has(x.id)))}if(!state.plan.connected&&incoming.plan.connected)state.plan=incoming.plan;else{const keys=new Set(state.plan.wins.map(w=>w.key));state.plan.wins.push(...incoming.plan.wins.filter(w=>!keys.has(w.key)))}render();toast('Backup imported. Existing entries were kept.')}catch(err){toast('Could not import: '+err.message)}finally{e.target.value=''}};
$('#clear').onclick=()=>{if(confirm('Delete all saved tasks, thoughts and routines here? Export a backup first if needed.')){stopRecording();state={...fresh(),routines:[]};render();$('#prefs').close();toast('Saved entries deleted.')}};
let recording=null,voiceBusy=false;
function stopRecording(){if(recording?.recorder.state==='recording')recording.recorder.stop()}
async function dictate(id,button){if(recording){stopRecording();return}if(voiceBusy){toast('Finishing your previous recording…');return}if(!state.localVoice){showSettings();return}if(!connection.voice){toast('Local speech model is not ready. Open AI & voice options to check.');return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('Recording is unavailable here. Open the localhost app in a browser with microphone support.');return}let field=document.getElementById(id);if(!field)return;let stream;voiceBusy=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});let mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m));let recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{}),chunks=[];recording={recorder,stream};voiceBusy=false;button.textContent='Stop';button.classList.add('listening');button.setAttribute('aria-pressed','true');$('#speech-status').textContent='Recording locally. Press Stop when finished.';let timer=setTimeout(stopRecording,90000);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>toast('Recording failed. Please try again.');recorder.onstop=async()=>{clearTimeout(timer);stream.getTracks().forEach(t=>t.stop());recording=null;voiceBusy=true;button.textContent='Transcribing…';button.disabled=true;try{const blob=new Blob(chunks,{type:recorder.mimeType});if(blob.size<100)throw Error('No audio recorded. Try again.');let r=await fetch('/api/transcribe',{method:'POST',headers:{'Content-Type':recorder.mimeType||'audio/webm'},body:blob,signal:AbortSignal.timeout(120000)});let data=await r.json();if(!r.ok)throw Error(data.error||'Transcription failed.');if(!data.text?.trim())throw Error('No speech detected. Try speaking closer to the microphone.');if(!field.isConnected)throw Error('The entry was closed. Please dictate again in the current field.');const numeric=field.getAttribute('inputmode')==='numeric';if(numeric){let n=spokenNumber(data.text);if(n===null)throw Error(`Heard “${data.text}”. Please type the number of minutes.`);field.value=String(n)}else{const full=(field.value.trim()?field.value.trim()+' ':'')+data.text.trim();field.value=field.maxLength>0?full.slice(0,field.maxLength):full;}field.dispatchEvent(new Event('input',{bubbles:true}));field.focus();toast('Words added. Review before saving.')}catch(err){toast(err.name==='NotAllowedError'?'Microphone permission was denied.':err.message)}finally{voiceBusy=false;button.disabled=false;button.textContent='Dictate';button.classList.remove('listening');button.setAttribute('aria-pressed','false');$('#speech-status').textContent='Recording stopped.'}};recorder.start();}catch(err){voiceBusy=false;if(stream)stream.getTracks().forEach(t=>t.stop());toast(err.name==='NotAllowedError'?'Microphone access was denied. Enable it in your browser to dictate.':'Could not start recording: '+err.message)}}
function spokenNumber(s){s=s.toLowerCase().replace(/[.,!?]/g,'').replace(/\b(minutes?|mins?)\b/g,'').trim();if(/^\d+$/.test(s))return +s;let ones={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};let n=0;for(let w of s.split(/[ -]+/)){if(w==='and')continue;if(w==='hundred'){n*=100;continue}if(!(w in ones))return null;n+=ones[w]}return n;}
window.addEventListener('pagehide',()=>{if(recording){recording.stream.getTracks().forEach(t=>t.stop());recording=null}});$$('dialog').forEach(d=>d.addEventListener('close',stopRecording));document.addEventListener('visibilitychange',()=>{if(!document.hidden){syncDay();renderRoutines()}});$('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});render();refreshConnection();
