(function(root){
'use strict';
const dateKey=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&dateKey(new Date(s+'T12:00:00'))===s;
const validTime=s=>typeof s==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(s);
const addDays=(s,n)=>{let d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return dateKey(d)};
const monday=s=>{let d=new Date(s+'T12:00:00');return addDays(s,-((d.getDay()+6)%7))};
const stamp=(date,time='00:00')=>new Date(date+'T'+time+':00').getTime();
const timeKey=ms=>{let d=new Date(ms);return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
const fmt=n=>{n=Math.max(0,Math.round(n));return n<60?`${n}m`:n%60?`${Math.floor(n/60)}h ${n%60}m`:`${n/60}h`};
const defaults=()=>({selectedDate:dateKey(new Date()),week:monday(dateKey(new Date())),settings:{workStart:'09:00',workEnd:'17:00',personalStart:'17:30',personalEnd:'21:00',workMinutes:360,personalMinutes:120,weekendMinutes:240,buffer:60,gap:10,workDays:[1,2,3,4,5]},calendars:[],events:[],connected:false,lastSync:0,syncError:'',wins:[],easyDays:[],reminders:false,reminderSeen:[],publishCalendar:''});
const clamp=(n,a,b,d)=>Number.isFinite(+n)?Math.max(a,Math.min(b,Math.round(+n))):d;
function normalizePlan(p){const def=defaults();p=p||{};let s=p.settings||{};return {...def,selectedDate:def.selectedDate,week:def.week,settings:{...def.settings,...Object.fromEntries(['workStart','workEnd','personalStart','personalEnd'].map(k=>[k,validTime(s[k])?s[k]:def.settings[k]])),workMinutes:clamp(s.workMinutes,0,720,360),personalMinutes:clamp(s.personalMinutes,0,720,120),weekendMinutes:clamp(s.weekendMinutes,0,720,240),buffer:clamp(s.buffer,0,240,60),gap:clamp(s.gap,0,60,10),workDays:Array.isArray(s.workDays)?s.workDays.filter(d=>Number.isInteger(d)&&d>=0&&d<=6):def.settings.workDays},calendars:Array.isArray(p.calendars)?p.calendars.slice(0,50).map(c=>({id:String(c.id),title:String(c.title),source:String(c.source||''),writable:!!c.writable,enabled:!!c.enabled,domain:c.domain==='work'?'work':'personal'})):[],events:Array.isArray(p.events)?p.events.filter(e=>typeof e.title==='string'&&Number.isFinite(e.start)&&Number.isFinite(e.end)&&e.end>e.start).slice(0,2000):[],connected:!!p.connected,lastSync:+p.lastSync||0,rangeStart:+p.rangeStart||0,rangeEnd:+p.rangeEnd||0,syncError:String(p.syncError||''),wins:Array.isArray(p.wins)?p.wins.filter(w=>typeof w.key==='string'&&validDate(w.date)).slice(-5000):[],easyDays:Array.isArray(p.easyDays)?p.easyDays.filter(validDate):[],reminders:!!p.reminders,reminderSeen:Array.isArray(p.reminderSeen)?p.reminderSeen.slice(-1000):[],publishCalendar:String(p.publishCalendar||'')};}
function taskFields(t,date=dateKey(new Date())){return {date:validDate(t.date)?t.date:t.date===''?'':date,start:validTime(t.start)?t.start:'',domain:t.domain==='work'?'work':'personal',reminder:clamp(t.reminder,0,1440,10),routineKey:String(t.routineKey||''),calendarEventId:String(t.calendarEventId||''),publishedCalendar:String(t.publishedCalendar||''),publishedFingerprint:String(t.publishedFingerprint||'')};}
function merge(ranges){const a=ranges.filter(r=>r[1]>r[0]).map(r=>[...r]).sort((a,b)=>a[0]-b[0]),out=[];for(const r of a){let last=out.at(-1);if(last&&r[0]<=last[1])last[1]=Math.max(last[1],r[1]);else out.push(r)}return out;}
function eventList(plan,tasks,date){const a=stamp(date),b=stamp(addDays(date,1));let calendars=new Map(plan.calendars.filter(c=>c.enabled).map(c=>[c.id,c]));return plan.events.filter(e=>calendars.has(e.calendarId)&&e.start<b&&e.end>a).filter(e=>!tasks.some(t=>t.id===e.taskId&&t.date&&t.start&&Math.abs(stamp(t.date,t.start)-e.start)<1000&&Math.abs(stamp(t.date,t.start)+t.minutes*60000-e.end)<1000)).map(e=>({...e,domain:calendars.get(e.calendarId).domain,clipStart:Math.max(a,e.start),clipEnd:Math.min(b,e.end)}));}
function dayBudget(plan,date){const s=plan.settings,work=s.workDays.includes(new Date(date+'T12:00:00').getDay()),easy=plan.easyDays.includes(date);const workCap=work?s.workMinutes:0,personalCap=work?s.personalMinutes:s.weekendMinutes;let gross=workCap+personalCap,buffer=Math.min(s.buffer,gross);return {work:workCap,personal:personalCap,buffer,capacity:Math.max(0,Math.floor((gross-buffer)*(easy?.6:1))),easy,isWorkDay:work};}
function summarize(plan,tasks,date){let events=eventList(plan,tasks,date),daily=tasks.filter(t=>t.date===date),timed=events.filter(e=>!e.allDay&&e.busy!==false);let busy=merge(timed.map(e=>[e.clipStart,e.clipEnd])).reduce((a,r)=>a+(r[1]-r[0])/60000,0);let taskMinutes=daily.reduce((a,t)=>a+t.minutes,0),budget=dayBudget(plan,date);let parts={};for(const domain of ['work','personal'])parts[domain]=merge(timed.filter(e=>e.domain===domain).map(e=>[e.clipStart,e.clipEnd])).reduce((a,r)=>a+(r[1]-r[0])/60000,0)+daily.filter(t=>t.domain===domain).reduce((a,t)=>a+t.minutes,0);let blocks=[...timed.map(e=>({start:e.clipStart,end:e.clipEnd,title:e.title})),...daily.filter(t=>t.start).map(t=>({start:stamp(date,t.start),end:stamp(date,t.start)+t.minutes*60000,title:t.text}))].sort((a,b)=>a.start-b.start);let conflicts=[];for(let i=0;i<blocks.length;i++)for(let j=i+1;j<blocks.length&&blocks[j].start<blocks[i].end;j++)conflicts.push([blocks[i].title,blocks[j].title]);const used=Math.round(busy+taskMinutes),overallOver=Math.max(0,used-budget.capacity),domainOver={work:Math.max(0,parts.work-budget.work),personal:Math.max(0,parts.personal-budget.personal)};return {date,events,tasks:daily,busy:Math.round(busy),taskMinutes,used,...budget,parts,overallOver,domainOver,remaining:Math.max(0,budget.capacity-used),over:Math.max(overallOver,domainOver.work+domainOver.personal),conflicts,allDay:events.filter(e=>e.allDay),unscheduled:daily.filter(t=>!t.start&&!t.done).length};}
function windowFor(plan,date,domain){let s=plan.settings,isWork=dayBudget(plan,date).isWorkDay;if(domain==='work'&&!isWork)return null;return domain==='work'?[stamp(date,s.workStart),stamp(date,s.workEnd)]:isWork?[stamp(date,s.personalStart),stamp(date,s.personalEnd)]:[stamp(date,'09:00'),stamp(date,'21:00')];}
function findSlot(plan,tasks,task,date,now=Date.now(),preferLate=false){let budget=summarize(plan,tasks,date),win=windowFor(plan,date,task.domain);if(!win||win[1]<=win[0]||task.minutes>budget.remaining||task.minutes+budget.parts[task.domain]>budget[task.domain])return null;let duration=task.minutes*60000,gap=plan.settings.gap*60000;let start=Math.max(win[0],date===dateKey(now)?Math.ceil(now/300000)*300000:win[0]);if(date<dateKey(now))return null;let blocked=merge([...budget.events.filter(e=>!e.allDay&&e.busy!==false).map(e=>[e.clipStart-gap,e.clipEnd+gap]),...tasks.filter(t=>t.date===date&&t.start).map(t=>[stamp(date,t.start)-gap,stamp(date,t.start)+t.minutes*60000+gap])]);let gaps=[];for(const [a,b]of blocked){if(b<=start)continue;if(a>start)gaps.push([start,Math.min(a,win[1])]);start=Math.max(start,b);if(start>=win[1])break}if(start<win[1])gaps.push([start,win[1]]);const fit=(preferLate?[...gaps].reverse():gaps).find(([a,b])=>b-a>=duration);if(!fit)return null;const at=preferLate?fit[1]-duration:fit[0];return {date,start:timeKey(at)};}
function propose(plan,tasks,candidates,dates,now=Date.now()){let ids=new Set(candidates.map(t=>t.id)),placed=[],unplaced=[],sim=tasks.filter(t=>!ids.has(t.id));for(const task of [...candidates].sort((a,b)=>a.priority-b.priority)){let found;const allowed=task.date&&dates.includes(task.date)?[task.date]:dates;for(const d of allowed){const slot=findSlot(plan,sim,task,d,now,task.routineKey?.includes('close'));if(slot){found={...task,...slot};break}}if(found){sim.push(found);placed.push(found)}else unplaced.push(task)}return {placed,unplaced};}
function makeICS(tasks){const escape=s=>String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const utc=ms=>new Date(ms).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//A little easier//Weekly plan//EN','CALSCALE:GREGORIAN'];for(const t of tasks.filter(t=>t.date&&t.start&&!t.done)){let start=stamp(t.date,t.start);lines.push('BEGIN:VEVENT',`UID:${escape(t.id)}@alittleeasier.local`,`DTSTAMP:${utc(Date.now())}`,`DTSTART:${utc(start)}`,`DTEND:${utc(start+t.minutes*60000)}`,`SUMMARY:${escape(t.text)}`,'DESCRIPTION:Flexible plan from A little easier.',`CATEGORIES:${t.domain==='work'?'Work':'Personal'}`,'BEGIN:VALARM',`TRIGGER:-PT${t.reminder||0}M`,'ACTION:DISPLAY',`DESCRIPTION:${escape(t.text)}`,'END:VALARM','END:VEVENT')}lines.push('END:VCALENDAR');return lines.map(line=>{let pieces=[],part='',n=0;for(const c of line){let size=new TextEncoder().encode(c).length;if(n+size>73){pieces.push(part);part=' ';n=1}part+=c;n+=size}pieces.push(part);return pieces.join('\r\n')}).join('\r\n')+'\r\n';}
const api={dateKey,validDate,validTime,addDays,monday,stamp,timeKey,fmt,defaults,normalizePlan,taskFields,merge,eventList,dayBudget,summarize,findSlot,propose,makeICS};if(typeof module!=='undefined')module.exports=api;else root.Planning=api;
})(typeof window!=='undefined'?window:globalThis);
